# .streamlit/secrets.toml

# Remote database for logging (optional)
log_db_url = "https://your-api-endpoint.com/submit"
api_token = "super-secret-token-123"

# App metadata (optional)
app_name = "HER2 Q&A Chatbot"
maintainer = "yourname@example.com"
